import { useState, useEffect, useRef } from "react";
import { toast } from "sonner";
import { Bike, MapPin, Package, CheckCircle2, Loader2, Wallet, Navigation, History, RefreshCw, FileCheck2, Wifi, WifiOff, AlertCircle } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { trpc } from "@/providers/trpc";

const money = (v: string | number | null | undefined) => `K${Number(v || 0).toLocaleString("en-ZM", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

function ErrorCard({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return <div className="bg-white rounded-2xl border border-red-100 p-5 text-center"><AlertCircle className="w-7 h-7 text-red-500 mx-auto mb-2" /><p className="font-bold text-peza-brown">We couldn't load this section</p><p className="text-xs text-gray-500 mt-1">{message}</p>{onRetry && <button onClick={onRetry} className="mt-3 inline-flex items-center gap-2 text-xs font-extrabold text-peza-orange"><RefreshCw className="w-3.5 h-3.5" /> Try again</button>}</div>;
}

export default function RiderDashboard() {
  const { user, session, isLoading: authLoading, error: authError, refresh } = useAuth({ redirectOnUnauthenticated: true });
  const utils = trpc.useUtils();
  const [sharingLocation, setSharingLocation] = useState(false);
  const [locationError, setLocationError] = useState<string | null>(null);
  const [tab, setTab] = useState<"home" | "history">("home");
  const [vehicleType, setVehicleType] = useState("");
  const [vehicleRegistration, setVehicleRegistration] = useState("");
  const [serviceArea, setServiceArea] = useState("Lusaka");
  const [notes, setNotes] = useState("");
  const watchIdRef = useRef<number | null>(null);
  const isRider = user?.role === "rider";

  const applicationQuery = trpc.rider.applicationStatus.useQuery(undefined, { enabled: !!session && !isRider, refetchInterval: 15000, retry: 2 });
  const apply = trpc.rider.apply.useMutation({ onSuccess: async (result) => { toast.success(result.message); await applicationQuery.refetch(); }, onError: (err) => toast.error(err.message || "Couldn't submit your rider application") });
  const updateLocation = trpc.rider.updateLocation.useMutation({ onError: (err) => toast.error(err.message || "Location update failed") });
  const goOffline = trpc.rider.goOffline.useMutation();
  const earningsQuery = trpc.rider.earnings.useQuery(undefined, { enabled: isRider, refetchInterval: 15000, retry: 2 });
  const availableQuery = trpc.rider.availableOrders.useQuery(undefined, { enabled: isRider, refetchInterval: 8000, retry: 2 });
  const deliveriesQuery = trpc.rider.myDeliveries.useQuery(undefined, { enabled: isRider, refetchInterval: 8000, retry: 2 });
  const historyQuery = trpc.rider.history.useQuery(undefined, { enabled: isRider, retry: 2 });

  const claimOrder = trpc.rider.claimOrder.useMutation({ onSuccess: async () => { toast.success("Delivery claimed — navigation is ready."); await Promise.all([availableQuery.refetch(), deliveriesQuery.refetch(), earningsQuery.refetch()]); }, onError: (err) => toast.error(err.message || "Couldn't claim this delivery") });
  const markDelivered = trpc.rider.markDelivered.useMutation({ onSuccess: async () => { toast.success("Marked as delivered!"); await Promise.all([deliveriesQuery.refetch(), historyQuery.refetch(), earningsQuery.refetch()]); }, onError: (err) => toast.error(err.message || "Couldn't update this delivery") });

  const stopSharing = () => {
    if (watchIdRef.current !== null && navigator.geolocation) navigator.geolocation.clearWatch(watchIdRef.current);
    watchIdRef.current = null;
    setSharingLocation(false);
    goOffline.mutate(undefined, { onError: () => undefined });
  };

  useEffect(() => () => { if (watchIdRef.current !== null && navigator.geolocation) navigator.geolocation.clearWatch(watchIdRef.current); }, []);

  const toggleSharing = () => {
    if (sharingLocation) { stopSharing(); toast.success("You're offline now."); return; }
    if (!navigator.geolocation) { setLocationError("Location isn't available on this device/browser."); toast.error("Location isn't available on this device/browser"); return; }
    setLocationError(null);
    let firstFix = true;
    watchIdRef.current = navigator.geolocation.watchPosition(
      (pos) => {
        setLocationError(null);
        if (firstFix) { firstFix = false; setSharingLocation(true); toast.success("You're online — live location sharing is active."); }
        updateLocation.mutate({ lat: pos.coords.latitude, lng: pos.coords.longitude });
      },
      (err) => { stopSharing(); const message = err.code === 1 ? "Location permission was denied. Allow location access to go online." : err.message || "Couldn't get your location."; setLocationError(message); toast.error(message); },
      { enableHighAccuracy: true, maximumAge: 10000, timeout: 15000 },
    );
  };

  const submitApplication = (e: React.FormEvent) => { e.preventDefault(); if (!vehicleType.trim() || !serviceArea.trim()) { toast.error("Enter your vehicle type and service area"); return; } apply.mutate({ vehicleType, vehicleRegistration: vehicleRegistration || undefined, serviceArea, notes: notes || undefined }); };

  if (authLoading) return <div className="min-h-screen bg-[#f7f7f5] px-4 py-12"><div className="max-w-md mx-auto bg-white rounded-3xl border border-gray-100 shadow-sm p-8 text-center"><Bike className="w-10 h-10 text-peza-orange mx-auto mb-4 animate-pulse" /><h1 className="text-xl font-extrabold text-peza-brown">Loading your rider account</h1><p className="text-sm text-gray-500 mt-2">Securing your session and loading your delivery workspace…</p><Loader2 className="w-5 h-5 animate-spin text-peza-orange mx-auto mt-5" /></div></div>;
  if (session && !user && authError) return <div className="min-h-screen bg-[#f7f7f5] px-4 py-12"><div className="max-w-md mx-auto bg-white rounded-3xl border border-red-100 shadow-sm p-8 text-center"><Bike className="w-10 h-10 text-red-500 mx-auto mb-4" /><h1 className="text-xl font-extrabold text-peza-brown">Rider account could not load</h1><p className="text-sm text-gray-500 mt-2">Your sign-in is active, but your PEZA profile could not be loaded.</p><button onClick={() => refresh()} className="mt-5 inline-flex items-center justify-center gap-2 w-full py-3 bg-peza-orange text-white rounded-xl font-bold text-sm"><RefreshCw className="w-4 h-4" /> Try again</button></div></div>;

  if (!isRider) {
    if (applicationQuery.isLoading) return <div className="max-w-md mx-auto px-4 pt-16 text-center"><Loader2 className="w-8 h-8 animate-spin text-peza-orange mx-auto" /><p className="text-sm text-gray-500 mt-3">Checking your rider application…</p></div>;
    if (applicationQuery.error) return <div className="max-w-md mx-auto px-4 pt-12"><ErrorCard message={applicationQuery.error.message} onRetry={() => applicationQuery.refetch()} /></div>;
    const application = applicationQuery.data;
    if (application?.status === "pending") return <div className="max-w-lg mx-auto px-4 py-10"><div className="bg-white rounded-3xl border border-amber-200 shadow-sm p-7 text-center"><div className="w-16 h-16 rounded-2xl bg-amber-50 flex items-center justify-center mx-auto mb-4"><FileCheck2 className="w-8 h-8 text-amber-600" /></div><h1 className="text-2xl font-extrabold text-peza-brown">Application under review</h1><p className="text-sm text-gray-500 mt-2">Your rider application has been submitted. PEZA will review it before you can accept deliveries.</p><div className="mt-6 text-left bg-peza-cream rounded-2xl p-4 space-y-2 text-sm"><p><span className="text-gray-500">Vehicle:</span> <strong>{application.application?.vehicleType}</strong></p><p><span className="text-gray-500">Service area:</span> <strong>{application.application?.serviceArea}</strong></p>{application.application?.vehicleRegistration && <p><span className="text-gray-500">Registration:</span> <strong>{application.application.vehicleRegistration}</strong></p>}</div><button onClick={() => applicationQuery.refetch()} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-peza-orange"><RefreshCw className="w-4 h-4" /> Refresh status</button></div></div>;
    return <div className="max-w-lg mx-auto px-4 py-8"><div className="text-center mb-6"><div className="w-20 h-20 rounded-3xl bg-peza-orange/10 flex items-center justify-center mx-auto mb-4"><Bike className="w-10 h-10 text-peza-orange" /></div><h1 className="text-2xl font-extrabold text-peza-brown">Become a PEZA Rider</h1><p className="text-sm text-gray-500 mt-2">Apply to deliver orders, earn per trip and build a flexible delivery business with PEZA.</p></div><form onSubmit={submitApplication} className="bg-white rounded-3xl border border-gray-100 shadow-sm p-5 space-y-4"><div><label className="text-xs font-bold text-peza-brown">Vehicle type</label><select value={vehicleType} onChange={(e) => setVehicleType(e.target.value)} className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm bg-white"><option value="">Select vehicle</option><option>Motorcycle</option><option>Bicycle</option><option>Car</option><option>Van</option><option>Truck</option></select></div><div><label className="text-xs font-bold text-peza-brown">Vehicle registration <span className="font-normal text-gray-400">(optional)</span></label><input value={vehicleRegistration} onChange={(e) => setVehicleRegistration(e.target.value)} placeholder="e.g. ABC 1234" className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm" /></div><div><label className="text-xs font-bold text-peza-brown">Primary service area</label><input value={serviceArea} onChange={(e) => setServiceArea(e.target.value)} placeholder="e.g. Lusaka" className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm" /></div><div><label className="text-xs font-bold text-peza-brown">Additional information <span className="font-normal text-gray-400">(optional)</span></label><textarea value={notes} onChange={(e) => setNotes(e.target.value)} maxLength={500} rows={3} placeholder="Tell us anything useful about your availability or delivery experience" className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm resize-none" /></div><button type="submit" disabled={apply.isPending} className="w-full py-3.5 bg-peza-orange text-white rounded-xl font-extrabold text-sm disabled:opacity-50">{apply.isPending ? "Submitting application…" : "Submit rider application"}</button><p className="text-[11px] text-gray-400 text-center">Your rider role is only activated after PEZA approval.</p></form></div>;
  }

  const earnings = earningsQuery.data;
  const availableOrders = availableQuery.data || [];
  const myDeliveries = deliveriesQuery.data || [];
  const history = historyQuery.data || [];

  return <div className="min-h-screen bg-[#f7f7f5] pb-10"><header className="bg-peza-brown text-white px-4 pt-5 pb-6 rounded-b-[28px] shadow-sm"><div className="max-w-3xl mx-auto"><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] text-white/60 uppercase tracking-wider font-bold">PEZA Rider</p><h1 className="text-2xl font-extrabold">Good to see you, {user?.name?.split(" ")[0] || "Rider"}</h1></div><button onClick={toggleSharing} disabled={goOffline.isPending} className={`shrink-0 px-4 py-2.5 rounded-full text-xs font-extrabold flex items-center gap-2 ${sharingLocation ? "bg-peza-green text-white" : "bg-white/10 text-white"}`}><span className={`w-2 h-2 rounded-full ${sharingLocation ? "bg-white animate-pulse" : "bg-white/40"}`} />{sharingLocation ? "ONLINE" : "GO ONLINE"}</button></div><div className="grid grid-cols-2 gap-3 mt-5"><div className="bg-white/10 rounded-2xl p-4"><div className="flex items-center gap-2 text-white/60 text-xs"><Wallet className="w-4 h-4" /> Earnings</div><p className="text-2xl font-extrabold mt-1">{earningsQuery.isLoading ? "…" : money(earnings?.total)}</p></div><div className="bg-white/10 rounded-2xl p-4"><div className="flex items-center gap-2 text-white/60 text-xs"><Navigation className="w-4 h-4" /> Completed trips</div><p className="text-2xl font-extrabold mt-1">{earningsQuery.isLoading ? "…" : earnings?.trips || 0}</p></div></div></div></header>
    <main className="max-w-3xl mx-auto px-4 -mt-3"><div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-1 flex"><button onClick={() => setTab("home")} className={`flex-1 py-2.5 rounded-xl text-sm font-bold ${tab === "home" ? "bg-peza-orange text-white" : "text-gray-500"}`}>Trips</button><button onClick={() => setTab("history")} className={`flex-1 py-2.5 rounded-xl text-sm font-bold ${tab === "history" ? "bg-peza-orange text-white" : "text-gray-500"}`}>History</button></div>
      {tab === "home" ? <>
        <div className="mt-4 bg-white rounded-2xl border border-gray-100 p-4 flex items-center gap-3"><div className={`w-10 h-10 rounded-full flex items-center justify-center ${sharingLocation ? "bg-green-50" : "bg-peza-cream"}`}>{sharingLocation ? <Wifi className="w-5 h-5 text-peza-green" /> : <WifiOff className="w-5 h-5 text-peza-orange" />}</div><div className="flex-1"><p className="font-bold text-sm text-peza-brown">{sharingLocation ? "You're online" : "You're offline"}</p><p className="text-xs text-gray-500">{sharingLocation ? "Live location is active and delivery offers will refresh automatically." : "Go online to receive delivery opportunities."}</p></div><span className={`text-[10px] font-extrabold px-2 py-1 rounded-full ${sharingLocation ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"}`}>{sharingLocation ? "LIVE" : "OFFLINE"}</span></div>
        {locationError && <div className="mt-3 bg-red-50 border border-red-100 rounded-2xl p-3 text-xs text-red-700 flex items-start gap-2"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{locationError}</span></div>}
        <section className="mt-5"><div className="flex items-center justify-between mb-2"><h2 className="font-extrabold text-peza-brown">Active trip</h2>{myDeliveries.length > 0 && <span className="text-xs font-bold text-peza-green">LIVE</span>}</div>{deliveriesQuery.isLoading ? <Loader2 className="w-5 h-5 animate-spin text-gray-400 mx-auto my-6" /> : deliveriesQuery.error ? <ErrorCard message={deliveriesQuery.error.message} onRetry={() => deliveriesQuery.refetch()} /> : myDeliveries.length ? <div className="space-y-3">{myDeliveries.map((order) => <div key={order.id} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-extrabold text-peza-brown">{order.orderNumber}</p><p className="text-xs text-gray-500 mt-1 truncate">{order.deliveryAddress}</p><p className="text-xs text-gray-500">{order.deliveryPhone}</p></div><span className="font-extrabold text-peza-orange shrink-0">{money(order.riderEarning)}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => order.deliveryLat != null && order.deliveryLng != null && window.open(`https://www.google.com/maps/dir/?api=1&destination=${order.deliveryLat},${order.deliveryLng}`, "_blank")} disabled={order.deliveryLat == null || order.deliveryLng == null} className="py-2.5 rounded-xl border border-gray-200 text-sm font-bold flex items-center justify-center gap-2 disabled:opacity-40"><Navigation className="w-4 h-4" /> Navigate</button><button onClick={() => markDelivered.mutate({ orderId: order.id })} disabled={markDelivered.isPending} className="py-2.5 rounded-xl bg-peza-green text-white text-sm font-bold flex items-center justify-center gap-2 disabled:opacity-50">{markDelivered.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}{markDelivered.isPending ? "Updating…" : "Delivered"}</button></div></div>)}</div> : <div className="bg-white rounded-2xl border border-dashed border-gray-200 p-7 text-center"><Package className="w-8 h-8 mx-auto text-gray-300 mb-2" /><p className="font-bold text-peza-brown">No active trip</p><p className="text-xs text-gray-400 mt-1">Claim a delivery below when one is available.</p></div>}</section>
        <section className="mt-6"><div className="flex items-center justify-between mb-2"><h2 className="font-extrabold text-peza-brown">Delivery opportunities</h2><button onClick={() => availableQuery.refetch()} className="p-2 rounded-xl hover:bg-white" aria-label="Refresh deliveries"><RefreshCw className={`w-4 h-4 text-peza-orange ${availableQuery.isFetching ? "animate-spin" : ""}`} /></button></div>{!sharingLocation ? <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 text-center"><MapPin className="w-7 h-7 text-amber-600 mx-auto mb-2" /><p className="font-bold text-amber-900">Go online to receive deliveries</p><p className="text-xs text-amber-800/70 mt-1">Allow location access so PEZA can support live trip matching.</p></div> : availableQuery.isLoading ? <Loader2 className="w-5 h-5 animate-spin text-gray-400 mx-auto my-6" /> : availableQuery.error ? <ErrorCard message={availableQuery.error.message} onRetry={() => availableQuery.refetch()} /> : availableOrders.length ? <div className="space-y-2">{availableOrders.map((order) => <div key={order.id} className="bg-white rounded-2xl border border-gray-100 p-4 flex items-center gap-3"><div className="w-11 h-11 shrink-0 rounded-xl bg-peza-cream flex items-center justify-center"><Package className="w-5 h-5 text-peza-brown" /></div><div className="flex-1 min-w-0"><p className="font-bold text-sm text-peza-brown">{order.orderNumber}</p><p className="text-xs text-gray-500 truncate">{order.deliveryAddress}</p><p className="text-xs text-gray-400 mt-0.5">Shipping {money(order.shipping)}</p></div><button onClick={() => claimOrder.mutate({ orderId: order.id })} disabled={claimOrder.isPending} className="bg-peza-orange text-white px-3.5 py-2 rounded-xl text-xs font-extrabold disabled:opacity-50">{claimOrder.isPending ? "Claiming…" : "Claim"}</button></div>)}</div> : <p className="text-sm text-gray-400 bg-white rounded-2xl p-6 text-center">No delivery opportunities right now. Keep the app online and we'll refresh automatically.</p>}</section>
      </> : <section className="mt-5"><div className="flex items-center gap-2 mb-3"><History className="w-5 h-5 text-peza-orange" /><h2 className="font-extrabold text-peza-brown">Trip history</h2></div>{historyQuery.isLoading ? <Loader2 className="w-5 h-5 animate-spin text-gray-400 mx-auto my-6" /> : historyQuery.error ? <ErrorCard message={historyQuery.error.message} onRetry={() => historyQuery.refetch()} /> : history.length ? <div className="space-y-2">{history.map((order) => <div key={order.id} className="bg-white rounded-2xl border border-gray-100 p-4 flex items-center gap-3"><div className="w-10 h-10 shrink-0 rounded-full bg-green-50 flex items-center justify-center"><CheckCircle2 className="w-5 h-5 text-peza-green" /></div><div className="flex-1 min-w-0"><p className="font-bold text-sm text-peza-brown">{order.orderNumber}</p><p className="text-xs text-gray-500 truncate">{order.deliveryAddress}</p><p className="text-[11px] text-gray-400 mt-1">{new Date(order.createdAt).toLocaleDateString("en-ZM")}</p></div><div className="text-right shrink-0"><p className="font-extrabold text-peza-orange">{money(order.riderEarning)}</p></div></div>)}</div> : <p className="text-sm text-gray-400 bg-white rounded-2xl p-6 text-center">Completed trips will appear here.</p>}</section>}
    </main></div>;
}
