import { useState } from "react";
import { trpc } from "@/providers/trpc";
import { toast } from "sonner";

export default function Vendor() {
  const products = trpc.vendor.products.useQuery();
  const summary = trpc.vendor.salesSummary.useQuery();
  const add = trpc.vendor.addProduct.useMutation({ onSuccess: () => { toast.success("Product added"); products.refetch(); }, onError: e => toast.error(e.message) });
  const [form, setForm] = useState({ name: "", description: "", price: "", stock: "", categorySlug: "" });
  return <main className="max-w-5xl mx-auto px-4 space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-peza-orange">Seller tools</p><h1 className="text-3xl font-extrabold text-peza-brown">Vendor dashboard</h1><p className="text-sm text-peza-brown/70">Manage your catalog and track sales securely.</p></header><section className="grid gap-4 sm:grid-cols-2"><div className="bg-peza-brown text-white rounded-2xl p-5"><p className="text-sm opacity-70">Orders</p><p className="text-3xl font-bold">{summary.data?.orders ?? 0}</p></div><div className="bg-white border rounded-2xl p-5"><p className="text-sm text-peza-brown/60">Revenue</p><p className="text-3xl font-bold text-peza-brown">K{Number(summary.data?.revenue ?? 0).toLocaleString()}</p></div></section><section className="bg-white border border-peza-cream-dark rounded-2xl p-5 space-y-3"><h2 className="font-bold">Add product</h2><div className="grid gap-3 sm:grid-cols-2"><input className="border rounded-lg px-3 py-2" placeholder="Product name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><input className="border rounded-lg px-3 py-2" placeholder="Category" value={form.categorySlug} onChange={e => setForm({ ...form, categorySlug: e.target.value })} /><textarea className="border rounded-lg px-3 py-2 sm:col-span-2" placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /><input className="border rounded-lg px-3 py-2" type="number" placeholder="Price" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} /><input className="border rounded-lg px-3 py-2" type="number" placeholder="Stock" value={form.stock} onChange={e => setForm({ ...form, stock: e.target.value })} /></div><button className="bg-peza-orange text-white rounded-lg px-4 py-2 font-semibold disabled:opacity-50" disabled={add.isPending} onClick={() => add.mutate({ ...form, price: Number(form.price), stock: Number(form.stock) })}>Add product</button></section><section className="space-y-3"><h2 className="font-bold text-xl">Your products</h2>{products.data?.map(product => <div className="bg-white border rounded-xl p-4 flex justify-between" key={product.id}><div><p className="font-semibold">{product.name}</p><p className="text-sm text-peza-brown/60">K{Number(product.price).toLocaleString()} · {product.stock} in stock</p></div><span className="text-xs text-peza-brown/50">#{product.id}</span></div>)}{products.data?.length === 0 && <p className="text-sm text-peza-brown/60">No products yet.</p>}</section></main>;
}
