import { useState } from "react";
import { useNavigate } from "react-router";
import { trpc } from "@/providers/trpc";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { Package, Plus, Pencil, Trash2, LogIn, TrendingUp, AlertTriangle, BarChart3 } from "lucide-react";

type ProductForm = { name: string; description: string; price: string; comparePrice: string; image: string; categorySlug: string; whatsappNumber: string; laybyMonths: string; stock: string };
const emptyForm: ProductForm = { name: "", description: "", price: "", comparePrice: "", image: "", categorySlug: "", whatsappNumber: "", laybyMonths: "", stock: "10" };
const fmtK = (n: number) => `K${n.toLocaleString()}`;

export default function Vendor() {
  const navigate = useNavigate();
  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<ProductForm>(emptyForm);
  const utils = trpc.useUtils();
  const { data: categories } = trpc.category.list.useQuery();
  const { data: myProducts } = trpc.vendor.myProducts.useQuery(undefined, { enabled: isAuthenticated });
  const { data: summary } = trpc.vendor.salesSummary.useQuery(undefined, { enabled: isAuthenticated });
  const { data: inventory } = trpc.vendor.inventory.useQuery(undefined, { enabled: isAuthenticated });
  const { data: topProducts } = trpc.vendor.topProducts.useQuery(undefined, { enabled: isAuthenticated });
  const addMutation = trpc.vendor.addProduct.useMutation({ onSuccess: () => { toast.success("Product listed"); utils.vendor.myProducts.invalidate(); utils.vendor.salesSummary.invalidate(); utils.vendor.inventory.invalidate(); setShowForm(false); setForm(emptyForm); }, onError: (err) => toast.error(err.message || "Couldn't save product") });
  const updateMutation = trpc.vendor.updateProduct.useMutation({ onSuccess: () => { toast.success("Product updated"); utils.vendor.myProducts.invalidate(); utils.vendor.inventory.invalidate(); setShowForm(false); setEditingId(null); setForm(emptyForm); }, onError: (err) => toast.error(err.message || "Couldn't update product") });
  const deleteMutation = trpc.vendor.deleteProduct.useMutation({ onSuccess: () => { toast.success("Product removed"); utils.vendor.myProducts.invalidate(); utils.vendor.salesSummary.invalidate(); utils.vendor.inventory.invalidate(); }, onError: (err) => toast.error(err.message || "Couldn't remove product") });

  if (!authLoading && !isAuthenticated) return <div className="max-w-md mx-auto px-4 py-16 text-center"><LogIn className="w-10 h-10 text-peza-orange mx-auto mb-3" /><h1 className="text-xl font-extrabold text-peza-brown mb-2">Sign in to sell on PEZA</h1><p className="text-sm text-gray-500 mb-5">List products, manage inventory and track sales.</p><button onClick={() => navigate("/login")} className="bg-peza-orange text-white font-bold px-6 py-3 rounded-xl">Log In</button></div>;

  function startEdit(p: NonNullable<typeof myProducts>[number]) { setEditingId(p.id); setForm({ name: p.name, description: p.description ?? "", price: p.price, comparePrice: p.comparePrice ?? "", image: p.image, categorySlug: p.categorySlug ?? "", whatsappNumber: p.whatsappNumber ?? "", laybyMonths: p.laybyMonths?.toString() ?? "", stock: p.stock.toString() }); setShowForm(true); }
  function submit() {
    if (!form.name.trim() || !form.price || !form.image.trim() || !form.categorySlug) return toast.error("Name, price, image, and category are required");
    const payload = { name: form.name.trim(), description: form.description.trim() || undefined, price: Number(form.price), comparePrice: form.comparePrice ? Number(form.comparePrice) : undefined, image: form.image.trim(), categorySlug: form.categorySlug, whatsappNumber: form.whatsappNumber.trim() || undefined, laybyMonths: form.laybyMonths ? Number(form.laybyMonths) : undefined, stock: Number(form.stock) || 0 };
    editingId ? updateMutation.mutate({ id: editingId, ...payload }) : addMutation.mutate(payload);
  }

  return <div className="max-w-6xl mx-auto px-4 pb-10">
    <div className="flex items-center justify-between mb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-peza-orange">Seller Centre</p><h1 className="text-2xl font-extrabold text-peza-brown">Vendor Dashboard</h1></div><button onClick={() => { setEditingId(null); setForm(emptyForm); setShowForm(!showForm); }} className="flex items-center gap-1.5 bg-peza-orange text-white text-sm font-bold px-4 py-2.5 rounded-xl"><Plus className="w-4 h-4" /> List Product</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5"><div className="bg-white rounded-2xl border border-gray-100 p-4"><p className="text-xs text-gray-500">Revenue</p><p className="text-xl font-extrabold text-peza-orange mt-1">{fmtK(summary?.totalRevenue ?? 0)}</p></div><div className="bg-white rounded-2xl border border-gray-100 p-4"><p className="text-xs text-gray-500">Units sold</p><p className="text-xl font-extrabold text-peza-brown mt-1">{summary?.unitsSold ?? 0}</p></div><div className="bg-white rounded-2xl border border-gray-100 p-4"><p className="text-xs text-gray-500">Listings</p><p className="text-xl font-extrabold text-peza-brown mt-1">{summary?.productCount ?? 0}</p></div><div className="bg-white rounded-2xl border border-gray-100 p-4"><p className="text-xs text-gray-500">Units in stock</p><p className="text-xl font-extrabold text-peza-brown mt-1">{inventory?.totalUnits ?? 0}</p></div></div>
    <div className="grid lg:grid-cols-3 gap-4 mb-6"><div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 p-4"><div className="flex items-center gap-2 mb-3"><BarChart3 className="w-5 h-5 text-peza-orange" /><h2 className="font-extrabold text-peza-brown">Top products</h2></div>{topProducts?.length ? <div className="space-y-2">{topProducts.map((p) => <div key={p.productId} className="flex items-center gap-3 border-b last:border-0 border-gray-100 py-2"><div className="flex-1 min-w-0"><p className="text-sm font-bold text-peza-brown truncate">{p.productName}</p><p className="text-xs text-gray-400">{p.unitsSold} units</p></div><span className="font-bold text-peza-orange">{fmtK(p.revenue)}</span></div>)}</div> : <p className="text-sm text-gray-400">Sales performance will appear after your first orders.</p>}</div><div className="bg-white rounded-2xl border border-gray-100 p-4"><div className="flex items-center gap-2 mb-3"><AlertTriangle className="w-5 h-5 text-amber-500" /><h2 className="font-extrabold text-peza-brown">Inventory alerts</h2></div>{inventory?.lowStock?.length ? <div className="space-y-2">{inventory.lowStock.slice(0, 6).map((p) => <div key={p.id} className="flex justify-between gap-2 text-sm"><span className="truncate text-peza-brown">{p.name}</span><b className="text-amber-600">{p.stock}</b></div>)}</div> : <p className="text-sm text-gray-400">No low-stock items.</p>}</div></div>
    {showForm && <div className="bg-white rounded-2xl border border-peza-cream-dark p-4 mb-6 space-y-3"><h2 className="font-bold text-peza-brown">{editingId ? "Edit Product" : "New Product"}</h2><input placeholder="Product name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /><textarea placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="w-full border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" rows={2} /><div className="grid grid-cols-2 gap-3"><input placeholder="Price (K)" type="number" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} className="border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /><input placeholder="Compare-at price" type="number" value={form.comparePrice} onChange={(e) => setForm({ ...form, comparePrice: e.target.value })} className="border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /></div><input placeholder="Image URL" value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} className="w-full border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /><select value={form.categorySlug} onChange={(e) => setForm({ ...form, categorySlug: e.target.value })} className="w-full border border-peza-cream-dark rounded-lg px-3 py-2 text-sm"><option value="">Select category</option>{categories?.map((c) => <option key={c.slug} value={c.slug}>{c.name}</option>)}</select><div className="grid grid-cols-3 gap-3"><input placeholder="WhatsApp number" value={form.whatsappNumber} onChange={(e) => setForm({ ...form, whatsappNumber: e.target.value })} className="border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /><input placeholder="Layby months" type="number" value={form.laybyMonths} onChange={(e) => setForm({ ...form, laybyMonths: e.target.value })} className="border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /><input placeholder="Stock" type="number" value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })} className="border border-peza-cream-dark rounded-lg px-3 py-2 text-sm" /></div><div className="flex gap-2"><button onClick={submit} disabled={addMutation.isPending || updateMutation.isPending} className="flex-1 bg-peza-orange text-white font-bold py-2.5 rounded-xl disabled:opacity-60">{editingId ? "Save Changes" : "List Product"}</button><button onClick={() => { setShowForm(false); setEditingId(null); setForm(emptyForm); }} className="px-4 py-2.5 rounded-xl border border-peza-cream-dark text-peza-brown font-semibold">Cancel</button></div></div>}
    <h2 className="font-bold text-peza-brown mb-3 flex items-center gap-2"><Package className="w-4 h-4" /> My Products</h2>
    {myProducts?.length ? <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{myProducts.map((p) => <div key={p.id} className="bg-white rounded-2xl border border-gray-100 p-3"><img src={p.image} alt={p.name} className="w-full aspect-[4/3] rounded-xl object-cover" /><div className="pt-3"><p className="font-semibold text-sm text-peza-brown truncate">{p.name}</p><p className="text-xs text-gray-500">K{Number(p.price).toLocaleString()} · Stock: {p.stock}</p><div className="flex gap-2 mt-3"><button onClick={() => startEdit(p)} className="flex-1 py-2 rounded-lg border border-gray-200 text-xs font-bold flex justify-center gap-1"><Pencil className="w-3.5 h-3.5" /> Edit</button><button onClick={() => { if (confirm(`Remove "${p.name}"?`)) deleteMutation.mutate({ id: p.id }); }} className="py-2 px-3 rounded-lg border border-red-200 text-red-500"><Trash2 className="w-3.5 h-3.5" /></button></div></div></div>)}</div> : <div className="text-center py-10 text-gray-400"><TrendingUp className="w-8 h-8 mx-auto mb-2" /><p className="text-sm">No products listed yet.</p></div>}
  </div>;
}
