import {
  pgTable, serial, text, integer, numeric, boolean, timestamp, uuid, jsonb,
} from "drizzle-orm/pg-core";

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(), name: text("name"), email: text("email"), phone: text("phone"),
  avatarUrl: text("avatar_url"), address: text("address"), city: text("city"), country: text("country").notNull().default("Zambia"),
  businessName: text("business_name"), businessType: text("business_type"), businessDescription: text("business_description"), website: text("website"),
  preferredLanguage: text("preferred_language").notNull().default("en"), role: text("role").notNull().default("customer"), createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const riderLocations = pgTable("rider_locations", { riderId: uuid("rider_id").primaryKey().references(() => profiles.id, { onDelete: "cascade" }), lat: numeric("lat").notNull(), lng: numeric("lng").notNull(), isOnline: boolean("is_online").notNull().default(true), updatedAt: timestamp("updated_at").notNull().defaultNow() });
export const categories = pgTable("categories", { id: serial("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), image: text("image"), parentId: integer("parent_id").references(() => categories.id, { onDelete: "set null" }), sortOrder: integer("sort_order").notNull().default(0), isActive: boolean("is_active").notNull().default(true), description: text("description") });
export const products = pgTable("products", { id: serial("id").primaryKey(), name: text("name").notNull(), slug: text("slug"), description: text("description"), price: numeric("price").notNull(), comparePrice: numeric("compare_price"), image: text("image").notNull(), realPhoto: text("real_photo"), categoryId: integer("category_id").references(() => categories.id), categorySlug: text("category_slug"), vendorId: uuid("vendor_id").references(() => profiles.id), vendor: text("vendor").notNull().default("PEZA Marketplace"), rating: numeric("rating").notNull().default("4.5"), reviewCount: integer("review_count").notNull().default(0), whatsappNumber: text("whatsapp_number"), laybyMonths: integer("layby_months"), featured: boolean("featured").notNull().default(false), isDeal: boolean("is_deal").notNull().default(false), stock: integer("stock").notNull().default(100), createdAt: timestamp("created_at").notNull().defaultNow() });
export const orders = pgTable("orders", { id: serial("id").primaryKey(), userId: uuid("user_id").notNull().references(() => profiles.id), orderNumber: text("order_number").notNull().unique(), subtotal: numeric("subtotal").notNull(), shipping: numeric("shipping").notNull(), discount: numeric("discount").notNull().default("0"), total: numeric("total").notNull(), paymentMethod: text("payment_method").notNull(), paymentReference: text("payment_reference"), deliveryAddress: text("delivery_address").notNull().default(""), deliveryPhone: text("delivery_phone").notNull().default(""), deliveryLat: numeric("delivery_lat"), deliveryLng: numeric("delivery_lng"), riderId: uuid("rider_id").references(() => profiles.id), riderEarning: numeric("rider_earning").notNull().default("0"), status: text("status").notNull().default("pending"), createdAt: timestamp("created_at").notNull().defaultNow() });
export const orderItems = pgTable("order_items", { id: serial("id").primaryKey(), orderId: integer("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), productId: integer("product_id").notNull().references(() => products.id), productName: text("product_name").notNull(), productImage: text("product_image"), price: numeric("price").notNull(), quantity: integer("quantity").notNull(), total: numeric("total").notNull() });
export const walletTransactions = pgTable("wallet_transactions", { id: serial("id").primaryKey(), userId: uuid("user_id").notNull().references(() => profiles.id), amount: numeric("amount").notNull(), type: text("type").notNull(), status: text("status").notNull().default("completed"), provider: text("provider"), providerReference: text("provider_reference"), description: text("description"), createdAt: timestamp("created_at").notNull().defaultNow() });
export const suppliers = pgTable("suppliers", { id: serial("id").primaryKey(), name: text("name").notNull(), image: text("image"), city: text("city").notNull(), country: text("country").notNull(), verified: boolean("verified").notNull().default(false), rating: numeric("rating").notNull().default("4.5"), description: text("description"), minOrder: text("min_order"), leadTime: text("lead_time"), category: text("category").notNull().default("All") });
export const marketPrices = pgTable("market_prices", { id: serial("id").primaryKey(), category: text("category").notNull(), item: text("item").notNull(), price: text("price").notNull(), change: text("change").notNull().default("0%"), isUp: boolean("is_up"), updatedAt: timestamp("updated_at").notNull().defaultNow(), source: text("source"), unit: text("unit").notNull().default("ZMW"), market: text("market") });
export const jobs = pgTable("jobs", { id: serial("id").primaryKey(), title: text("title").notNull(), company: text("company").notNull(), category: text("category").notNull(), location: text("location").notNull(), type: text("type").notNull(), salary: text("salary").notNull(), description: text("description"), requirements: jsonb("requirements").$type<string[]>().default([]), urgent: boolean("urgent").notNull().default(false), postedAt: timestamp("posted_at").notNull().defaultNow() });
export const jobApplications = pgTable("job_applications", { id: serial("id").primaryKey(), jobId: integer("job_id").notNull().references(() => jobs.id), userId: uuid("user_id").notNull().references(() => profiles.id), coverLetter: text("cover_letter"), createdAt: timestamp("created_at").notNull().defaultNow() });
export const chats = pgTable("chats", { id: serial("id").primaryKey(), userId: uuid("user_id").notNull().references(() => profiles.id), name: text("name").notNull(), avatar: text("avatar").notNull().default("S"), lastMsg: text("last_msg").notNull().default(""), unread: integer("unread").notNull().default(0), updatedAt: timestamp("updated_at").notNull().defaultNow() });
export const chatMessages = pgTable("chat_messages", { id: serial("id").primaryKey(), chatId: integer("chat_id").notNull().references(() => chats.id, { onDelete: "cascade" }), text: text("text").notNull(), isOutgoing: boolean("is_outgoing").notNull().default(true), createdAt: timestamp("created_at").notNull().defaultNow() });
export const notifications = pgTable("notifications", { id: serial("id").primaryKey(), userId: uuid("user_id").notNull().references(() => profiles.id), type: text("type").notNull().default("info"), title: text("title").notNull(), message: text("message").notNull(), read: boolean("read").notNull().default(false), createdAt: timestamp("created_at").notNull().defaultNow() });
export const infobipMessages = pgTable("infobip_messages", { id: serial("id").primaryKey(), provider: text("provider").notNull().default("infobip"), channel: text("channel").notNull().default("sms"), direction: text("direction").notNull().default("inbound"), sender: text("sender"), recipient: text("recipient"), externalId: text("external_id"), body: text("body").notNull(), status: text("status").notNull().default("received"), payload: jsonb("payload"), createdAt: timestamp("created_at").notNull().defaultNow() });
export const chilimbaCircles = pgTable("chilimba_circles", { id: serial("id").primaryKey(), name: text("name").notNull(), description: text("description"), contributionAmount: numeric("contribution_amount").notNull(), frequencyDays: integer("frequency_days").notNull().default(7), maxMembers: integer("max_members").notNull(), creatorId: uuid("creator_id").notNull().references(() => profiles.id), status: text("status").notNull().default("recruiting"), currentRound: integer("current_round").notNull().default(0), createdAt: timestamp("created_at").notNull().defaultNow() });
export const chilimbaMembers = pgTable("chilimba_members", { id: serial("id").primaryKey(), circleId: integer("circle_id").notNull().references(() => chilimbaCircles.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => profiles.id), payoutPosition: integer("payout_position").notNull(), hasBeenPaid: boolean("has_been_paid").notNull().default(false), joinedAt: timestamp("joined_at").notNull().defaultNow() });
export const chilimbaContributions = pgTable("chilimba_contributions", { id: serial("id").primaryKey(), circleId: integer("circle_id").notNull().references(() => chilimbaCircles.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => profiles.id), round: integer("round").notNull(), amount: numeric("amount").notNull(), createdAt: timestamp("created_at").notNull().defaultNow() });
export const adminAuditLog = pgTable("admin_audit_log", { id: serial("id").primaryKey(), actorId: uuid("actor_id").notNull().references(() => profiles.id), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: text("target_id").notNull(), detail: jsonb("detail"), createdAt: timestamp("created_at").notNull().defaultNow() });
export const chilimbaPayouts = pgTable("chilimba_payouts", { id: serial("id").primaryKey(), circleId: integer("circle_id").notNull().references(() => chilimbaCircles.id, { onDelete: "cascade" }), round: integer("round").notNull(), recipientId: uuid("recipient_id").notNull().references(() => profiles.id), amount: numeric("amount").notNull(), paidAt: timestamp("paid_at").notNull().defaultNow() });
